package br.com.pocketapps.RankIt.entities.enums;
public enum CategoriaEnum {
    DESENVOLVIMENTO_WEB("Desenvolvimento Web"),
    CIENCIA_DE_DADOS("Ciência de Dados"),
    INTELIGENCIA_ARTIFICIAL("Inteligência Artificial"),
    MACHINE_LEARNING("Machine Learning"),
    PYTHON("Python"),
    JAVA("Java"),
    DESENVOLVIMENTO_APLICATIVOS_MOBILE("Desenvolvimento de Aplicativos Móveis"),
    SEGURANCA_DA_INFORMACAO("Segurança da Informação"),
    BLOCKCHAIN("Blockchain"),
    CLOUD_COMPUTING("Cloud Computing"),
    REDES_DE_COMPUTADORES("Redes de Computadores"),
    SISTEMAS_OPERACIONAIS("Sistemas Operacionais"),
    INTERNET_DAS_COISAS("Internet das Coisas"),
    DESENVOLVIMENTO_DE_JOGOS("Desenvolvimento de Jogos"),
    REALIDADE_VIRTUAL_E_AUMENTADA("Realidade Virtual e Aumentada"),
    DESIGN_DE_INTERFACE_DO_USUARIO("Design de Interface do Usuário"),
    DESIGN_DE_EXPERIENCIA_DO_USUARIO("Design de Experiência do Usuário"),
    MARKETING_DIGITAL("Marketing Digital"),
    SEO("SEO"),
    GESTAO_DE_PROJETOS_DE_SOFTWARE("Gestão de Projetos de Software"),
    DEVOPS("DevOps"),
    BANCO_DE_DADOS_SQL("Banco de Dados SQL"),
    NOSQL("NoSQL"),
    BIG_DATA("Big Data"),
    ANALISE_DE_DADOS("Análise de Dados"),
    REDES_NEURAIS("Redes Neurais"),
    LINGUAGEM_DE_PROGRAMACAO_R("Linguagem de Programação R"),
    CIBERSEGURANCA("Cibersegurança"),
    AUTOMATIZACAO_DE_TESTES_DE_SOFTWARE("Automatização de Testes de Software"),
    DESENVOLVIMENTO_AGIL("Desenvolvimento Ágil"),
    CIENCIA_DA_COMPUTACAO("Ciência da Computação"),
    BUSINESS_INTELLIGENCE("Business Intelligence"),
    ANALISE_DE_NEGOCIOS("Análise de Negócios"),
    DESIGN_GRAFICO("Design Gráfico"),
    FOTOGRAFIA_DIGITAL("Fotografia Digital"),
    EDICAO_DE_VIDEO("Edição de Vídeo"),
    MARKETING_DE_CONTEUDO("Marketing de Conteúdo"),
    FINANCAS_PESSOAIS("Finanças Pessoais"),
    INGLES_PARA_NEGOCIOS("Inglês para Negócios"),
    PSICOLOGIA_ORGANIZACIONAL("Psicologia Organizacional"),
    LIDERANCA_E_GESTAO_DE_EQUIPES("Liderança e Gestão de Equipes"),
    COMUNICACAO_EFICAZ("Comunicação Eficaz"),
    NEGOCIACAO("Negociação"),
    GESTAO_DO_TEMPO("Gestão do Tempo"),
    ESTRATEGIA_DE_NEGOCIOS("Estratégia de Negócios"),
    EMPREENDEDORISMO("Empreendedorismo"),
    ECONOMIA_COMPORTAMENTAL("Economia Comportamental"),
    MARKETING_DE_REDES_SOCIAIS("Marketing de Redes Sociais"),
    DESENVOLVIMENTO_PESSOAL("Desenvolvimento Pessoal"),
    COACHING_PROFISSIONAL("Coaching Profissional"),
    DESENVOLVIMENTO_DE_SOFTWARE("Desenvolvimento de Software"),
    PROGRAMACAO_EM_C_PLUS_PLUS("Programação em C++"),
    INTERNET_SEGURA("Internet Segura"),
    REDACAO_TECNICA("Redação Técnica"),
    DESIGN_RESPONSIVO("Design Responsivo"),
    LINGUAGEM_SWIFT("Linguagem Swift"),
    ARQUITETURA_DE_SOFTWARE("Arquitetura de Software"),
    COMPUTACAO_QUANTICA("Computação Quântica"),
    ANALISE_DE_SISTEMAS("Análise de Sistemas"),
    BUSINESS_ANALYTICS("Business Analytics"),
    REDACAO_CIENTIFICA("Redação Científica"),
    METODOS_AGILE("Métodos Ágeis"),
    ESTRUTURAS_DE_DADOS("Estruturas de Dados"),
    FRONT_END_DEVELOPMENT("Front-end Development"),
    BACK_END_DEVELOPMENT("Back-end Development"),
    UX_UI_DESIGN("UX/UI Design"),
    MOBILE_UI_UX_DESIGN("Mobile UI/UX Design"),
    TESTES_DE_SOFTWARE("Testes de Software"),
    SISTEMAS_EMBARCADOS("Sistemas Embarcados"),
    PYTHON_PARA_DATA_SCIENCE("Python para Data Science"),
    DESENVOLVIMENTO_DE_APIS("Desenvolvimento de APIs"),
    DESENVOLVIMENTO_AGIL_DE_SOFTWARE("Desenvolvimento Ágil de Software"),
    REDES_SOCIAIS_E_MARKETING("Redes Sociais e Marketing"),
    ESTRATEGIAS_DE_NEGOCIOS_DIGITAIS("Estratégias de Negócios Digitais"),
    ESTATISTICA_PARA_CIENCIA_DE_DADOS("Estatística para Ciência de Dados"),
    FLUTTER("Flutter (Desenvolvimento Móvel)"),
    KOTLIN("Kotlin (Linguagem de Programação)"),
    BANCO_DE_DADOS_NOSQL("Banco de Dados NoSQL"),
    METODOLOGIAS_DE_ENSINO_ONLINE("Metodologias de Ensino Online"),
    DESIGN_DE_PRODUTO("Design de Produto"),
    PROTOTIPAGEM_RAPIDA("Prototipagem Rápida"),
    CIENCIA_DA_COMPUTACAO_QUANTICA("Ciência da Computação Quântica"),
    DEEP_LEARNING("Deep Learning"),
    REDES_DE_BLOCKCHAIN("Redes de Blockchain"),
    GESTAO_DE_DADOS("Gestão de Dados"),
    ROBOTICA_AVANCADA("Robótica Avançada"),
    DESENVOLVIMENTO_DE_SOFTWARE_AGIL("Desenvolvimento de Software Ágil"),
    GESTAO_DE_RISCOS_EM_PROJETOS("Gestão de Riscos em Projetos"),
    UX_WRITING("UX Writing"),
    DESENVOLVIMENTO_DE_CHATBOTS("Desenvolvimento de Chatbots"),
    ESTRATEGIAS_DE_SEO_AVANCADAS("Estratégias de SEO Avançadas"),
    DESIGN_INCLUSIVO("Design Inclusivo"),
    SEGURANCA_EM_DISPOSITIVOS_MOVEIS("Segurança em Dispositivos Móveis"),
    PROGRAMACAO_FUNCIONAL("Programação Funcional"),
    ANALISE_DE_SENTIMENTOS("Análise de Sentimentos"),
    DESIGN_DE_EXPERIENCIA_EM_JOGOS("Design de Experiência em Jogos"),
    DESENVOLVIMENTO_DE_APLICACOES_DESKTOP("Desenvolvimento de Aplicações Desktop "),
    REDES_DE_SENSORES("Redes de Sensores"),
    ETICA_EM_INTELIGENCIA_ARTIFICIAL("Ética em Inteligência Artificial"),
    DESENVOLVIMENTO_DE_SISTEMAS_DISTRIBUIDOS("Desenvolvimento de Sistemas Distribuídos");

    private final String nome;

    CategoriaEnum(String nome) {
        this.nome = nome;
    }

    public String getNome() {
        return nome;
    }
}